version: '3.7'
services:
    exit-prototype-ui:
        container_name: exit-prototype-ui
        image: varasev/exit-prototype-ui
        volumes:
            - ./data:/app/data
            - ./key:/app/key
        ports:
            - "80:80"
        environment:
            PORT: 80
            RATIO_READ_INTERVAL: 600
            REBALANCE_INTERVAL: 3600
            REBALANCER_MAX_GAS_PRICE: 10000000000
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "10"