version: '3.7'
services:
    exit-prototype-ui:
        container_name: exit-prototype-ui
        image: varasev/exit-prototype-ui
        volumes:
            - ./data:/app/data
        ports:
            - "3000:3000"
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "10"